### PR TITLE
FLOE-566: Adding Create-a-Thon activity to the Guide.

### PR DESCRIPTION
**Pull request by jhung**
@michelled do you have time to look at this? I will update this entry later with a link to the CaT article on the ILDH once that is done.

### CODE REVIEW

**Comment by michelled** [comment]
@dayotte will take a look, thx @jhung

**Comment by dayotte** [comment]
@jhung 
- A small thing but I would add a comma after the word sameness here, since it's quite a long sentence: "It is important to avoid distilling user insights and stories to a collection of averages and eliminating individual differences in favour of sameness, because each story is as important as another and will contribute to rich designs and insights." 
- Also, I'm not a huge fan of the insertion of the "CaT" acronym into those 2 words (communiCaTe and voCaTion), though I like the idea. I think mostly because the two words have such different meaning - i.e. communicating is part of the CaT process, so I can see why it works there, but with vocation it makes less sense to me. But to have it in just one word might be strange. 
- I see your comment about adding the link to ILDH, just wondering if you'll put it under the Combine WIth section? or somewhere else?

**Comment by jhung** [comment]
Thanks @dayotte.

I fixed the punctuation and the random "CaT" appearing in those words (the result of a bad search and replace I did and wasn't intentional).

 I will be adding a link to the ILDH entry once that has been published.

**Comment by dayotte** [comment]
@jhung - that's funny about the CaT appearing, I just assumed it was intentional! :)

**Pull request merged**
