### PR TITLE
Minor typography fix

### PR DESCRIPTION
**Pull request by bliz-ward**

### CODE REVIEW

**Review by greatislander — CHANGES_REQUESTED** [review]
It's not clear to me what's been changed here.

**Comment by Julien-Ward** [comment]
Hi.
It might be because i'm using a latin character set in my web browser since
i'm french.
In some places, i had red dots or broken characters displaying in the
middle of words.
I hope that helps,
Julien

Le lun. 9 nov. 2020 à 14:24, Ned Zimmerman <notifications@github.com> a
écrit :

**Comment by greatislander** [comment]
@Julien-Ward Thanks for clarifying. I'll see if I can figure out what's causing this issue.

**Comment by greatislander** [comment]
@Julien-Ward Can you tell me what browser you are using? I'd like to see if I can reproduce your issue myself.

**Comment by jobara** [comment]
@greatislander if you look at the [rich diff](https://github.com/inclusive-design/guide.inclusivedesign.ca/pull/51/files?short_path=7c4b06f#diff-7c4b06f1c50db648d3f499fe19da03b401e3243ad795caf155679fdba9b02382) you can see the character. However, I can't see this at all in VS Code.

**Comment by bliz-ward** [comment]
hello,
I wanted to know if it could be useful to make a french translation of the
inclusive design guide and if so, how do you suggest I should do it?
Thank you,
Julien

Le jeu. 12 nov. 2020 à 14:59, Ned Zimmerman <notifications@github.com> a
écrit :

**Comment by greatislander** [comment]
@bliz-ward Thanks for these changes! In terms of making a translation, that would be fantastic— it sounds like we'll be getting a French translation of the article on ["Disability as Mismatch"](https://guide.inclusivedesign.ca/insights/disabilityasmismatch) produced by someone who's asked to reproduce it in a collection of bilingual resources.

In order to make the guide fully bilingual, we'll need to add multilingual support to the website. There's a related issue here: https://github.com/fluid-project/fluidic-11ty/issues/48

If you have interest in beginning to work on translations, I'd suggest collecting them in a shared Google Drive folder or something while we work on setting up the guide to work in multiple languages. Once that's done we can integrate your translations.

**Review by greatislander — APPROVED** [review]

**Pull request merged**
