### PR TITLE
feat: replace sidebar navigation with breadcrumb and landing page (Resolves #54, #68, #69)

### LINKED ISSUE #54: Replace sidebar navigation with breadcrumb and landing page navigation
Remove the sidebar navigation, and replace with a breadcrumb and landing page navigation. This will bring it in line with redesign of the ILDH, as well as make navigation more intuitive and usable for mobile.

This will address [FLOE-511 - "It's not obvious how to navigate back to the home/intro page of Design Guide"](https://issues.fluidproject.org/browse/FLOE-511), and remove older version of Infusion that is included in docs-core library (which we are trying to deprecate).

Mock-up: See comment below
Figma file: https://www.figma.com/file/X0m2dKT90dlPcYVw8VrRYu/Design-Guide-Navigation?node-id=0%3A1

### LINKED ISSUE #68: It's not obvious how to navigate back to the home/intro page of Design Guide
## Describe the bug
It's not obvious how to navigate to the Home page once viewing content in one of the four categories.

Originally filed as [FLOE-511](https://issues.fluidproject.org/browse/FLOE-511)

### LINKED ISSUE #69: Articles on the Design Guide should appear in alphabetical order when listed
## Describe the bug
When listing articles on the Design Guide, the articles should appear in alphabetical order.

Originally filed as [FLOE-485](https://issues.fluidproject.org/browse/FLOE-485)

## Additional context or notes
Some issues to consider:
* Should ordering be based on their short or long title if both are available, but have different starting letters?
* If alphabetical order is the convention, if article content has a list of links to other articles in the Guide, those should be alphabetically ordered as well.

### PR DESCRIPTION
**Pull request by jobara**
Resolves #54
Resolves #68 
Resolves #69 

I had originally thought there would be many changes needed to the styling to incorporate the breadcrumb designs; however, after further investigation I found that I could get close with a few minor changes. 

_**NOTE**: the colours for some of the cards were updated to ensure that the breadcrumbs were WCAG AA compliant for contrast_

### CODE REVIEW

**Comment by greatislander** [comment]
@jobara I see that the breadcrumb navigation is using an `aria-label` of "breadcrumb". Is "breadcrumb" well-understood outside of web design/development circles? I'm wondering if something else might be better. I don't have any ideas off the top of my head.
<details><summary>Browser metadata</summary>





```
Path:      /insights/insights
Browser:   Safari 14.1.2 on Mac OS 10.15.7
Viewport:  1268 x 858 @2x
Language:  en-ca
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-75--idrc-inclusive-design-guide.netlify.app%2Finsights%2Finsights&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1268x858&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-75--idrc-inclusive-design-guide.netlify.app/insights/insights) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=613a33e91d3f0d0007fa9e37&commentID=613a3a1552df0636235f0dad&resolution=resolved)

**Comment by greatislander** [comment]
@jobara What do you think of using a single right-pointing angle bracket (›) instead of a greater-than symbol? I think it looks a bit better.

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /insights/insights
Browser:   Safari 14.1.2 on Mac OS 10.15.7
Viewport:  1268 x 858 @2x
Language:  en-ca
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-75--idrc-inclusive-design-guide.netlify.app%2Finsights%2Finsights&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1268x858&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-75--idrc-inclusive-design-guide.netlify.app/insights/insights) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=613a33e91d3f0d0007fa9e37&commentID=613a3ad84f0e414d820e1faf&resolution=resolved)

**Comment by jobara** [comment]
> @jobara I see that the breadcrumb navigation is using an `aria-label` of "breadcrumb". Is "breadcrumb" well-understood outside of web design/development circles? I'm wondering if something else might be better. I don't have any ideas off the top of my head.
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-75--idrc-inclusive-design-guide.netlify.app/insights/insights) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=613a33e91d3f0d0007fa9e37&commentID=613a3a1552df0636235f0dad&resolution=resolved)

That's a good questions. I don't have a definitive answer. I did look around a bit. 

- [WAI-ARIA breadcrumb](https://w3c.github.io/aria-practices/examples/breadcrumb/index.html) example uses "Breadcrumb"
- the [11ty documentation site](https://www.11ty.dev/docs/pagination/nav/) uses "Breadcrumbs:"
- the [MDN](https://developer.mozilla.org/en-US/docs/Web/Guide) site uses "Breadcrumb navigation"
- the [CNIB](https://www.cnib.ca/en/sight-loss-info/clearing-our-path?region=on) site uses "Breadcrumb"

For now I'll make it start with a capital at least, but let me know if you have thoughts on further modifications.

**Comment by jobara** [comment]
@greatislander I've made the changes. Ready for more review.

**Review by greatislander — APPROVED** [review]
Looks good!

**Pull request merged**
